### ISSUE TITLE
Can't decode encoded string with � character

### ISSUE THREAD

**Issue by Robert-Rendell** [One-com/rfc2047#4]
https://runkit.com/robert-rendell/5f7c762377e1d10019fc362f
```

var rfc2047 = require("rfc2047")

const a = 'test_�.docx';
const b = rfc2047.encode(a);

const c = rfc2047.decode(b)

console.log("b: " + b);
console.log("c: " + c);
console.log("c should equal a, does it? ", c == a);
```

output

```
"b: =?utf-8?Q?test_=EF=BF=BD=2Ed?=ocx"
"c: =?utf-8?Q?test_=EF=BF=BD=2Ed?=ocx"
"c should equal a, does it? "
false
```

**Comment by papandreou** [comment]
This turned out to be the same problem as #3 -- the difference between `c` and `a` is the underscore. So also fixed in 3.0.0.

**Comment by Robert-Rendell** [comment]
I'm afraid I still get the same result with version 3.0.0:

https://runkit.com/robert-rendell/5f7cd33577e1d10019fd0b85

**Comment by papandreou** [comment]
That's weird, I actually added it as a unit test: https://github.com/One-com/rfc2047/blob/aba37b2c21015c1a7f263a4fc6c0fa2212e00440/test/rfc2047.js#L122-L128

Not sure why it doesn't work in runkit.

**Comment by papandreou** [comment]
Ah, I get it now, there's a fast path that only gets exercised when decoding utf-8 *and* when `iconv` isn't available (it is in dev). In that case the replacement character is explicitly used to detect a decoding error: https://github.com/One-com/rfc2047/blob/aba37b2c21015c1a7f263a4fc6c0fa2212e00440/lib/rfc2047.js#L92-L94 🤦

**Comment by papandreou** [comment]
Try 3.0.1 :)

**Comment by Robert-Rendell** [comment]
Working! Thank you again!
